use_frameworks!

platform:'ios', 15.0

target '${POD_NAME}_Example' do
  pod '${POD_NAME}', :path => '../'

  target '${POD_NAME}Tests' do
    inherit! :search_paths

    ${INCLUDED_PODS}
  end

  target '${POD_NAME}UITests' do
    inherit! :search_paths

    ${INCLUDED_PODS}
  end

end

